In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [2]:
dataset = pd.read_csv("datafortestingpurposes.csv")
dataset.info

<bound method DataFrame.info of      Age  Sex  CPT  RPB  SCH  FBS  RES  MHR  EIA  OPK  PES  VCA  THA  T
0     63    1    1  145  233    1    2  150    0  2.3    3    0    6  0
1     67    1    4  160  286    0    2  108    1  1.5    2    3    3  2
2     67    1    4  120  229    0    2  129    1  2.6    2    2    7  1
3     37    1    3  130  250    0    0  187    0  3.5    3    0    3  0
4     41    0    2  130  204    0    2  172    0  1.4    1    0    3  0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ..
298   45    1    1  110  264    0    0  132    0  1.2    2    0    7  1
299   68    1    4  144  193    1    0  141    0  3.4    2    2    7  2
300   57    1    4  130  131    0    0  115    1  1.2    2    1    7  3
301   57    0    2  130  236    0    2  174    0  0.0    2    1    3  1
302   38    1    3  138  175    0    0  173    0  0.0    1    0    3  0

[303 rows x 14 columns]>

In [3]:
print(np.unique(dataset[['CPT']].values))
print(np.unique(dataset[['VCA']].values))
print(np.unique(dataset[['VCA']].values))

[1 2 3 4]
[0 1 2 3]
[0 1 2 3]


In [4]:
dataset = pd.get_dummies(dataset, columns=['Sex', 'CPT', 'FBS', 'RES', 'EIA', 'PES', 'VCA','THA'])
standardScaler = StandardScaler()
columns_to_scale = ['Age', 'RPB','MHR', 'OPK']
dataset[columns_to_scale] = standardScaler.fit_transform(dataset[columns_to_scale])

In [5]:
dataset.head()

Age       RPB  SCH       MHR       OPK  T  Sex_0  Sex_1  CPT_1  CPT_2  \
0  0.948726  0.757525  233  0.017197  1.087338  0      0      1      1      0   
1  1.392002  1.611220  286 -1.821905  0.397182  2      0      1      0      0   
2  1.392002 -0.665300  229 -0.902354  1.346147  1      0      1      0      0   
3 -1.932564 -0.096170  250  1.637359  2.122573  0      0      1      0      0   
4 -1.489288 -0.096170  204  0.980537  0.310912  0      1      0      0      1   

   ...  PES_2  PES_3  VCA_0  VCA_1  VCA_2  VCA_3  THA_0  THA_3  THA_6  THA_7  
0  ...      0      1      1      0      0      0      0      0      1      0  
1  ...      1      0      0      0      0      1      0      1      0      0  
2  ...      1      0      0      0      1      0      0      0      0      1  
3  ...      0      1      1      0      0      0      0      1      0      0  
4  ...      0      0      1      0      0      0      0      1      0      0  

[5 rows x 30 columns]

In [6]:
y = dataset['T']
X = dataset.drop(['T'], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing


from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn import datasets

In [8]:
knn_scores = []
for k in range(1, 40):
    knn_classifier = KNeighborsClassifier(n_neighbors=k)
    knn_classifier.fit(X_train, y_train)
    knn_scores.append(knn_classifier.score(X_test, y_test))
print(f'Best score of k:{np.argmax(knn_scores)+1}')


Best score of k:5


In [9]:
k = 5
knn_classifier = KNeighborsClassifier(n_neighbors=k)
knn_classifier.fit(X_train, y_train)
y_pred = knn_classifier.predict(X_test)
print(f'Accuracy:{np.sum(y_pred == y_test)/len(y_test)}')

Accuracy:0.5245901639344263


In [10]:
svc_scores=[]
kernels =['linear', 'poly', 'rbf', 'sigmoid']
for i in range(len(kernels)):
    svc_scores_c = []
    for ch in range(1,11):
        if kernels[i] == 'poly':
            svc_scores_poly = []
            for d in range (3, 10):
                svc_classifier = SVC(kernel = kernels[i], C=ch, degree=d)
                svc_classifier.fit(X_train, y_train)
                svc_scores_poly.append(svc_classifier.score(X_test, y_test))
            print(f'Best polynomial score: {np.argmax(svc_scores_poly)+3}')
            svc_scores_c.append(svc_scores_poly[np.argmax(svc_scores_poly)])
        else:
            svc_classifier = SVC(kernel = kernels[i], C=ch)
            svc_classifier.fit(X_train, y_train)
            svc_scores_c.append(svc_classifier.score(X_test, y_test))
    print(f'Best choice of c for {kernels[i]}: {np.argmax(svc_scores_c)+1}')
    svc_scores.append(svc_scores_c[np.argmax(svc_scores_c)])
print(f'Best choice of k:{kernels[np.argmax(svc_scores)]}')

Best choice of c for linear: 2
Best polynomial score: 3
Best polynomial score: 3
Best polynomial score: 3
Best polynomial score: 9
Best polynomial score: 9
Best polynomial score: 9
Best polynomial score: 8
Best polynomial score: 8
Best polynomial score: 8
Best polynomial score: 8
Best choice of c for poly: 4
Best choice of c for rbf: 1
Best choice of c for sigmoid: 1
Best choice of k:linear
